version: '3.9'

services:
  kotlinapp:
    container_name: sysinfoserver
    image: pavelhanzl/sysinfoserver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - db

  kotlinapp2:
    container_name: sysinfoclient
    image: pavelhanzl/sysinfoclient
    build:
      context: ../../sysinfoclient/sysinfoclient
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}